services:
  postgres:
    image: postgres:15
    container_name: demo_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demo_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  zookeeper:
    image: zookeeper:3.9
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_CLIENT_PORT: 2181
    volumes:
      - zk_data:/data
      - zk_datalog:/datalog

  kafka:
    image: apache/kafka:3.7.2
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    user: "root"                  
    ports:
      - "9093:9093"
    volumes:
      - kafka_data:/tmp/kafka-logs
      - ./certs:/etc/kafka/certs:ro
      - ./server.properties:/opt/kafka/config/server.properties:ro
    
    # Bypass the broken Docker bash scripts and boot Kafka directly
    entrypoint:
      - /opt/kafka/bin/kafka-server-start.sh
      - /opt/kafka/config/server.properties

volumes:
  kafka_data:
  zk_data:
  zk_datalog:
  pgdata: